export const GET_SELECTED_REPO_PENDING = 'GET_SELECTED_REPO_PENDING';
export const GET_SELECTED_REPO_RESOLVED = 'GET_SELECTED_REPO_RESOLVED';
export const GET_SELECTED_REPO_REJECTED = 'GET_SELECTED_REPO_REJECTED';
export const GET_SELECTED_REPO_README_PENDING = 'GET_SELECTED_REPO_README_PENDING';
export const GET_SELECTED_REPO_README_RESOLVED = 'GET_SELECTED_REPO_README_RESOLVED';
export const GET_SELECTED_REPO_README_REJECTED = 'GET_SELECTED_REPO_README_REJECTED';
export const CLEAR_REDUCER = 'CLEAR_REDUCER';

export const BASE_URL = '/repos/';
